### PR TITLE
Small spelling: artefact to artifact

### PR DESCRIPTION
**Pull request by shanselman**

### CODE REVIEW

**Comment by trailmax** [comment]
thank you!

**Comment by shanselman** [comment]
Sure. Since it changes the artifact directory name, do make sure that if you have any config in AppVeyor that you are aware!

**Comment by trailmax** [comment]
The directories are defined in separate parameters file: https://github.com/AMVSoftware/NSaga/blob/master/parameters.cake#L4 I could not push into this branch, so quickly fixed it in master -)

**Comment by shanselman** [comment]
Gotcha, not sure how I missed that. Thanks!

**Pull request merged**
